version: 2.1

jobs:
    test:
        description: "Run tests"
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk:2.1
        steps:
            - checkout
            - run:
                name: "Install project dependencies"
                command: dotnet restore
            - run:
                name: "Run Application Tests"
                command: dotnet test
    build:
        environment:
            IMAGE_NAME: codeframes
            TAG: 1.0.0
        docker:
            - image: docker:stable-git
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build Image
                command: docker build -t efevans/$IMAGE_NAME:$TAG .
            - run:
                name: Push Image
                command: |
                    echo "$_docker_hub_password_" | docker login -u "$_docker_hub_username_" --password-stdin
                    docker push efevans/$IMAGE_NAME:$TAG
workflows:
    test_build_push:
        jobs:
            - test
            - build:
                requires:
                    - test