version: 1
jobs:
    build:
        environment:
            IMAGE_NAME: codeframes
            TAG: 1.0.0
        docker:
            - image: circleci/ruby:latest
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build and push Docker image
                command: |
                    docker build -t efevans/$IMAGE_NAME:$TAG .
                    echo "$_docker_hub_password_" | docker login -u "$_docker_hub_username_" --password-stdin
                    docker push efevans/$IMAGE_NAME:$TAG
            